### ISSUE TITLE
ray_mesh_intersect python function doesn't work as expected 

### ISSUE THREAD

**Issue by iszihan** [libigl/libigl-python-bindings#106] opened 2021-10-16 16:04 UTC
Hello, 

The ray_mesh_intersect function gives segmentation fault on every odd vertex, and an abnormally long list of hits for the others vertex that doesn't give seg fault. It would be much appreciated if someone can look into what is wrong. Thank you in advance!

**Comment by iszihan** [comment] 2021-10-16 19:49
Here is a minimal script that has this behavior with vith the sphere.obj here [https://drive.google.com/file/d/1E8IPf1Ge_A-eBuUDSyh2LKous3f4d66G/view?usp=sharing](url)
```
import igl 
​
m_in_v, _, m_in_n, m_in_f, _, _ =  igl.read_obj("./sphere.obj") # sphere
nv = len(m_in_v)
for i in range(nv):
    print(i)
    hit = igl.ray_mesh_intersect(m_in_v[i], -m_in_n[i], m_in_v, m_in_f)
```

**Comment by alecjacobson** [comment] 2021-10-16 23:21
Still debugging, but somehow when python sends the list of vertex positions to ray_mesh_intersect its entries are being read incorrectly w.r.t column-major and row-major.

**Comment by alecjacobson** [comment] 2021-10-16 23:50
I believe I found the issue. This line

https://github.com/libigl/libigl-python-bindings/blob/3c3a6ea8f6c95720f76c9b4d8c5a26b6c8330235/src/ray_mesh_intersect.cpp#L40

doesn't make sense. `source` is a single point and `v` should be a matrix containing vertices on rows.

Meanwhile, I'm also suspicious about this `npe_matches` function. It seems to be defined the NumpyEigen external dependency as simply:

```
#define npe_matches(x) dense_float
```

https://github.com/fwilliams/numpyeigen/blob/96c6356102a9f6c6eca5dd5446c4513552c12da9/src/npe.h#L115

**Comment by alecjacobson** [comment] 2021-10-17 00:27
So, the `npe_matches` appears to be the reason that it was returning so many hits (the vertex positions were scrambled so it was a nonsense mesh).

Unfortunately, there's another issue. The first argument `m_in_v[i]` is causing a memory violation. This is likely due to a bug/issue with the way that NumpyEigen creates `Eigen::Maps`. Perhaps, it's failing to create a valid map around the ith row and this is causing a memory issue. The hot fix is to change `m_in_v[i]` to `m_in_v[i].copy()`.

**Comment by alecjacobson** [comment] 2023-02-06 00:37
perhaps duplicate of #78

**Closed** 2023-09-25 13:28 UTC

**Comment by zaczhuozhang** [comment] 2023-11-24 12:36
```python
from igl import ray_mesh_intersect  # type: ignore # It is a C++ binding.
from numpy import array

v = array([[-5.0, -5.0, 0.0], [5.0, -5.0, 0.0], [5.0, 5.0, 0.0], [-5.0, 5.0, 0.0]], dtype=float)
f = array([[0, 1, 3], [1, 2, 3]], dtype=int)

p = array([-4.0, 1.0, 5.0], dtype=float)
dir = array([0, 0, -1], dtype=float)

print( ray_mesh_intersect(p, dir, v, f))
```
looks the same problem? `t =8.0` but apparent it should be `5`

**Comment by alecjacobson** [comment] 2023-11-24 17:53
This is fixed in dev.

i get 5 on version 2.5.5dev

**Comment by alecjacobson** [comment] 2023-11-24 18:02
(and now it works with latest 2.5.0)
